baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Wise Wisdom'
theme = 'ananke'









DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true


[params]
  text_color = ""
  author = "Frank"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5



[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
